### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by dlp-dev-composant** [8468/bitboot#1]
node -v
v11.14.0

```yarn init -y```
```yarn add bitboot```
```nano index.js```

```
// index.js

var Bitboot = require('bitboot')
 
// The rally point name can be any string and should be unique
// to your peer network
var bb = new Bitboot('bitboot test network')
 
// this is called whenever the node selects a new ID and rejoins
// the BitTorrent mainline DHT network
bb.on('rejoin', function (nodeId) {
  console.log('I have a new node id:', nodeId.toString('hex'))
})
 
// this is called whenever a search is made for peers
// peers will be the result of that search (and may be empty)
bb.on('peers', function (peers) {
  console.log('I found peers:', peers)
})
 
bb.on('error', function (err) {
  console.error(err)
})

```

```DEBUG=bitbootnode index.js```

```bitboot Using rally point bitboot test network (9bfe9630481ea6bc5851f4ea9aeb164e15497a24) +0ms
  bitboot Joining network with id 9bfe8cd199e4d134ea5834c088d8b66056157a24 (distance to rally 2.341762075932748e+42) +8ms
I have a new node id: 9bfe8cd199e4d134ea5834c088d8b66056157a24
  bitboot Searching, and creating interval for future searches +3s
  bitboot Searching for nodes near rally point +1ms
/Users/parweb/Sites/atmosfear/node_modules/bitboot/index.js:101
  var closestdist = KBucket.distance(closest[0].id, this.rallyId)
                                                ^

TypeError: Cannot read property 'id' of undefined
    at Bitboot._attemptCommunication (/Users/parweb/Sites/atmosfear/node_modules/bitboot/index.js:101:49)
    at finished (/Users/parweb/Sites/atmosfear/node_modules/bitboot/index.js:93:15)
    at done (/Users/parweb/Sites/atmosfear/node_modules/k-rpc/index.js:240:5)
    at processTicksAndRejections (internal/process/task_queues.js:79:9)```

**Comment by bmuller** [comment]
@dlp-dev-composant - that error should only occur if you don't have any internet access (or if UDP is blocked).  I just added better messaging for that case.  Thanks!
